name: CD Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/securityteam12/pai-4:${{ github.ref_name }}  # Usa el nombre de la rama como tag
          labels: |
            org.opencontainers.image.source=https://github.com/SecurityTeam12/PAI-4

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:  # Define entornos en GitHub (Settings > Environments)
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ github.ref == 'refs/heads/main' && secrets.PROD_URL || secrets.STAGING_URL }}
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_IP || secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/securityteam12/pai-4:${{ github.ref_name }}
            docker-compose down
            docker-compose up -d
