name: CI

on:
  push:
    branches:
      - main
      - feat/CI-implementations

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'salmorejo-hub-2/uvlhub'

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          ref: feat/CI-implementations

      - name: Set up git
        run: |
          git config user.name "JuanluRM"
          git config user.email "juanluis.ruano.muriedas@gmail.com"

      - name: Add the parent repository as a remote
        run: |
          git remote add upstream https://github.com/salmorejo-hub/uvlhub.git
          git fetch upstream

      - name: Attempt to merge main into develop
        run: |
          git checkout -b temp-develop upstream/feat/CI-implementation
          git merge --no-ff feat/CI-implementations || echo "Merge conflict detected, skipping push"

      - name: Push changes if merge is successful
        if: success()
        run: |
          git push upstream temp-develop:feat/CI-implementation

      - name: Create a pull request if merge failed
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: "Sync main to Salmorejo-hub"
          body: |
            This pull request was created automatically because a direct merge from `main` to `develop` was not possible due to conflicts.
          base: feat/CI-implementation
          branch: CI/sync-hub-2
          delete-branch: true