name: CI1


permissions: 
    pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'salmorejo-hub-1/uvlhub'

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Set up git
        run: |
          git config user.name "Javier Santos"
          git config user.email "javsanmar5@us.es"

      - name: Add the parent repository as a remote
        run: |
          git remote add upstream https://github.com/salmorejo-hub/uvlhub.git
          git fetch upstream

      - name: Attempt to merge main into develop
        run: |
          git checkout -b temp-develop upstream/develop
          git merge --no-ff main --allow-unrelated-histories 

      - name: Push changes if merge is successful
        if: success()
        run: |
          git push upstream temp-develop:develop

      - name: Create a pull request if merge failed
        if: failure()
        run: |
          gh pr create \
            --repo salmorejo-hub/uvlhub \
            --head salmorejo-hub-1:main \
            --base develop \
            --title "CI/ Sync Salmorejo-hub-1 main to Salmorejo-hub develop" \
            --body "This PR syncs changes from main in salmorejo-hub-1 to develop in salmorejo-hub after discovering conflicts in the push and the @salmorejo-hub/Salmorejo-hub-1 team needs to resolve."

        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}