name: Push or Create PR on Conflict

on:
  push:
    branches:
      - main
      - feat/CI-implementations

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          repository: salmorejo-hub-2/uvlhub
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: feat/CI-implementations

      - name: Configure Git
        run: |
            git config pull.rebase false   
            git config user.email "juanluis.ruano.muriedas@gmail.com"
            git config user.name "JuanluRM"
      
      - name: Add parent repository as remote
        run: |
          git remote add parent https://github.com/salmorejo-hub/uvlhub.git
          git fetch parent

      - name: Pull parent develop into child main
        run: |
          git checkout feat/CI-implementations
          git pull parent feat/CI-implementation --allow-unrelated-histories
  
      - name: Check for conflicts
        run: |
          git diff --exit-code || echo "Conflict detected"
        continue-on-error: true
  
      - name: Push to parent develop if no conflicts
        if: success()
        run: |
          git push parent feat/CI-implementations:feat/CI-implementation
  
      - name: Create Pull Request if conflicts exist
        if: failure()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: "CI/ Resolve conflicts for integrations"
          body: "Can't automatically merge the changes into Salmorejo-hub, please resolve conflicts to continue"
          branch: feat/CI-implementation
