name: Sync to Parent Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-to-parent:
    name: Sync Changes to Parent Repository
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    # Step 1: Checkout the forked repository (salmorejo-hub-1)
    - name: Checkout salmorejo-hub-1 repository
      uses: actions/checkout@v3
      with:
        ref: main

    # Step 2: Configure SSH to use the Deploy Key
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 3: Fetch all branches to ensure synchronization
    - name: Fetch all branches
      run: |
        git fetch --all

    # Step 4: Configure Git identity
    - name: Set Git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "CI: GitHub Actions Bot"

    # Step 5: Add the parent repository as a remote
    - name: Add parent repository as upstream
      run: |
        git remote add upstream git@github.com:salmorejo-hub/uvlhub.git
        git fetch upstream

    - name: Checkout and prepare upstream develop
      run: |
        git fetch upstream develop
        git checkout -b temp-develop upstream/develop

    - name: Attempt to merge with fork main
      run: |
        git merge origin/main --allow-unrelated-histories --no-commit --no-ff
      continue-on-error: true

    - name: Check for merge conflicts
      if: failure()
      run: |
        echo "Merge conflict detected. Manual intervention required."
        echo "The following files have conflicts:"
        git diff --name-only --diff-filter=U
        exit 1

    - name: Push changes to parent develop
      if: success()
      run: |
        git commit -m "chore: AUTO merge from salmorejo-hub-1 to salmorejo-hub/uvlhub/develop"
        git push upstream temp-develop:develop
