name: Integrate with Parent Repository

on:
  push:
    branches:
      - main  # Se activa con cada push en la rama main del repositorio hijo

jobs:
  sync_with_parent:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "antjimort"
          git config --global user.email "antjimort@alum.us.es"
      - name: Check Git Remote and User
        run: |
          git remote -v
          git config --get user.name
          git config --get user.email
      - name: Add Parent Repository as Remote
        run: |
          git remote add parent https://github.com/salmorejo-hub/uvlhub.git
          git fetch parent

      - name: Push to Parent Repository
        run: |
          git remote set-url parent https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/salmorejo-hub/uvlhub.git
          git push parent main:develop
