name: Sync to Parent Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-to-parent:
    name: Sync Changes to Parent Repository
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    # Step 1: Checkout the forked repository (salmorejo-hub-1)
    - name: Checkout salmorejo-hub-1 repository
      uses: actions/checkout@v3
      with:
        ref: main

    # Step 2: Configure SSH to use the Deploy Key
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 3: Fetch all branches to ensure synchronization
    - name: Fetch all branches
      run: |
        git fetch --all

    # Step 4: Configure Git identity
    - name: Set Git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "CI: GitHub Actions Bot"

    # Step 5: Add the parent repository as a remote
    - name: Add parent repository
      run: |
        git remote add parent git@github.com:salmorejo-hub/uvlhub.git
        git fetch parent develop

    # Step 6: Attempt to push changes to parent/develop
    - name: Push changes to parent/develop
      run: |
        git push parent main:develop || echo "Push failed. Possible conflicts detected."

    # Step 7: Handle push failure
    - name: Notify conflicts if push fails
      if: failure()
      run: |
        echo "Push failed because the remote branch 'develop' has changes that conflict with 'main'."
        echo "The following files have conflicts:"
        git diff --name-only --diff-filter=U
        echo "Please resolve these conflicts manually and try again."

    # Step 8: Notify user if the push was successful
    - name: Notify success
      if: success()
      run: |
        echo "The push was successful and changes were synced to parent/develop."
