name: Create Pull Request to Parent Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Parent Repo
        run: |
          PARENT_REPO="git@github.com:salmorejo-hub/uvlhub.git"
          git clone $PARENT_REPO parent_repo
          cd parent_repo

          git config --global user.name "CI: GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync and Push Changes
        run: |
          cd parent_repo
          git fetch origin develop
          git checkout -b sync-from-child main
          git pull origin main || true
          git push origin sync-from-child

      - name: Create Pull Request
        run: |
          cd parent_repo
          BASE_BRANCH="develop"
          HEAD_BRANCH="sync-from-child"
          PR_TITLE="AUTOMATED PR: Sync salmorejo-hub-1 'main' with salmorejo-hub 'develop'"
          PR_BODY="This pull request was created automatically by salmorejo-hub-1."

          # Create a new PR
          gh pr create \
            --repo git@github.com:salmorejo-hub/uvlhub.git \
            --base $BASE_BRANCH \
            --head $HEAD_BRANCH \
            --title "$PR_TITLE" \
            --body "$PR_BODY"
