name: Deploy to Render

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:

  deploy:
    if: github.repository == 'salmorejo-hub/uvlhub'
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5


      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
